### PR TITLE
Initial skeleton of interactive rpc and socket

### PR DESCRIPTION
**Pull request by connor4312**
Going was a little slower than it might otherwise have been, had to relearn some asyncio stuff I'd forgotten 😛  Anyhow, this seems to work.

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]
Looks ok, although my python is not that great 😛

**Comment by capgames** [comment]
Seems all OK from my eye, one thing I might suggest is maybe renaming the repository to beam-interactive2-python, Some people may think this is for python 2 instead.

Personally I would have liked to see 3.4 compatibility. If you want I can work on a direct conversion for 3.4, I will have to do this anyways for running on raspberry pi

**Review by Purzifal — APPROVED** [review]
Seems all OK from my eye, one thing I might suggest is maybe renaming the repository to beam-interactive2-python, Some people may think this is for python 2 instead.

Personally I would have liked to see 3.4 compatibility. If you want I can work on a direct conversion for 3.4, I will have to do this anyways for running on raspberry pi

**Comment by connor4312** [comment]
@capgames are there scenarios where someone would choose to start a project with Python < 3.6? Python versions prior to 3.6 are no longer maintained outside of issuing security patches.

**Comment by Scrxtchy** [comment]
> `Some people may think this is for python 2`

I can admit to some confustion

**Comment by Purzifal** [comment]
@connor4312 only scenario I can say for sure is raspberry pi. It officially supports python 2.7.9 and 3.4.2 while you can build later builds they are not officially supported especially when it comes to rpi specific libraries. It's ok though I can backport what I need to

**Comment by connor4312** [comment]
Thanks for the feedback on naming. We've decided to:

 1. Rename all new interactive 2 repositories `interactive-${language}`. This repo is renamed "interactive-python"
 2. Keep the names on all old interactive 1 clients, but place visible deprecation notices where appropriate directing people to use interactive 2.

Regarding Python versions: it looks like Raspberry Pi's come bundled with 3.4, but compiling 3.6 from source [is possible](https://gist.github.com/dschep/24aa61672a2092246eaca2824400d37f). I think I'll stick with 3.5+ support here and provide a link to that gist or instructions for people on Raspberry Pis or older Python versions.

Thanks for all your feedback! I'm going to get this merged in.

**Pull request merged**
